### ISSUE TITLE
Could you please share the method of adding low visibility conditions to images?

### ISSUE THREAD

**Issue by Kongsea** [Achleshwar/lvrnet#1]
Thank you for your solid work.

You have mentioned that:

> We have used public [dataset AFO](https://www.kaggle.com/datasets/jangsienicajzkowy/afo-aerial-dataset-of-floating-objects) and generated our dataset - Low-Vis AFO, by adding low visibility conditions. You can download it [here](https://github.com/Achleshwar/lvrnet/blob/main).

So I want to know what method you used to generated the low visibility data and Could you please share it? Thank you.

**Comment by Achleshwar** [comment]
@Kongsea thank you for your interest in our work and sorry for the late reply! In this work, we mainly reported results on low-light + haze effects.

-  For low-light, we referred to this ICCV paper (https://github.com/cuiziteng/ICCV_MAET)
-  For haze effect, we have used imgaug library (https://github.com/aleju/imgaug)

You can find details about params used in our paper. Let me know if you have more questions!

**Comment by Kongsea** [comment]
OK, I will try. Thank you.

**Comment by rose-jinyang** [comment]
Hi @Achleshwar 
Image quality degradation occurs by other factors such as blur, artifact etc.
Could you add many factors as possible?
